Repository woboq/qmetaobject-rs, pull requests merged in 2021-09, with the labels that each got.

#196 Put qml_register_enum behind Qt5.8 guard
  qmetaobject/src/lib.rs
Labels: C-bug, A-rust

#198 Fix typos in qttypes crate-level documentation, and add some dots.
  qttypes/src/lib.rs
Labels: C-cleanup, A-docs

#199 Fix compilation with Qt 6.2 and MSVC
  qmetaobject/build.rs
  qttypes/build.rs
  qttypes/src/lib.rs
Labels: I-crash, O-windows-msvc, A-C++
